version: '3.0'
services:
        load01:
                build: loadbalancer
                hostname: load01
                container_name: load01
                volumes:
                        - ./loadbalancer/ssh:/root/.ssh
        app01:
                build: webserver
                hostname: app01
                container_name: app01
                volumes:
                        - ./webserver/ssh:/root/.ssh

        db01:
                build: db
                hostname: mysql01
                container_name: mysql01
                volumes:
                        - ./db/ssh:/root/.ssh
                environment:
                                MYSQL_ROOT_PASSWORD: 123456
                                MYSQL_DATABASE: auth
                                MYSQL_USER: admin
                                MYSQL_PASSWORD: admin
        ansible:
                build: control
                hostname: ansible
                container_name: ansible
                links:
                        - app01
                        - load01
                        - db01
                volumes:
                        - ./control/inventory:/etc/ansible
                        - ./control/ssh:/root/.ssh
                        - ./db/ssh:/root/shared/db/
                        - ./webserver/ssh:/root/shared/webserver/
                        - ./loadbalancer/ssh:/root/shared/loadbalancer/


